import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/utils";
import NavBar from "./components/NavBar";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EHR",
  description: "Generated by EHR",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "grid grid-cols-10 grid-rows-12 h-screen w-full",
          inter.className
        )}
      >
        <NavBar />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
